VERILOG = ulx3s_usbhost_test.v usb_phy.v usb_rx_phy.v usb_tx_phy.v \
	  hex_decoder_v.v usbh_sie.v usbh_crc5.v usbh_crc16.v \
	  lcd_video.v usbh_host_hid.v clk_25_125_48_6_25.v
IDCODE = 0x41113043 # 85
DEVICE = 85k

include ../ulx3s.mk



