VERILOG = top.v font_rom.v PushButton_Debouncer.v ../clk_25_250_125_25.v \
	  ../fake_differential.v ../hdmi_video.v ..//tmds_encoder.v ../vga2dvid.v ../vga_video.v \
	  attosoc.v picorv32.v simpleuart.v spi_master.v flash_write.v sdcard.v

DEVICE = 85k

include ../../ulx3s.mk


